### ISSUE TITLE
Set only specific months selectable

### ISSUE THREAD

**Issue by tenshi04** [KidSysco/jquery-ui-month-picker#64] opened 2016-09-23 19:47 UTC
Not really an issue - but I was wondering if there was a way to maybe pass json to specify which months are selectable? ie. I want the user to be able to select a month based on a set of 'valid' months.

**Comment by benjamin-albert** [comment] 2016-09-23 21:25
Take a look at the [MinMonth](https://github.com/KidSysco/jquery-ui-month-picker/wiki/MinMonth-Option) and [MaxMonth](https://github.com/KidSysco/jquery-ui-month-picker/wiki/MinMonth-Option) options.

**Comment by tenshi04** [comment] 2016-09-23 21:35
Can you provide an example where I can say something like such:

Cannot select: Feb 2015, March 2015, May 2015, June 2015, August 2015, Sept 2015, November 2015, Dec 2015
Can select:  Jan 2015, April 2015, July 2015, October 2015

**Comment by benjamin-albert** [comment] 2016-09-23 21:54
There is no built in support for disabling arbitrary months (and as far as I'm aware neither does jQuery UI Datepicker).

However it might be possible to use some of the [many events] this plugin offers to disable the month buttons.

Stay tuned while I try to make a fiddle for this.

@tenshi04 An example of the JSON coming from your server with the selectable months can help me provide a better example.

**Comment by benjamin-albert** [comment] 2016-09-23 23:41
Here is a working (in Chrome) [fiddle](http://jsfiddle.net/8x4nnvsj/4/) with a quick and dirty example of how to do this.

It was a bit more complicated then I originally thought because the `OnBeforeMenuOpen` event is triggered before the menu is properly setup, which means you need to subclass the plugin and override the `Open` method.

**Comment by benjamin-albert** [comment] 2016-09-23 23:47
Another thing to note, this example requires some refactoring to work properly if you have more than one instance of MonthPicker that requires this functionality on the page.

**Comment by tenshi04** [comment] 2016-09-24 01:39
I’ll definitely give it a try. I only need one month-year picker on the page so that makes things easier.

Thank you!

**Comment by KidSysco** [comment] 2016-09-25 21:06
Very nice code Ben. I never thought I would see anyone using those events. Your key system is very well put together. I never would have thought of that. Very impressive.

**Comment by tenshi04** [comment] 2016-09-26 14:47
I got it setup but having issues disabling the buttons with this line I believe:

$('.button-' + i, menu).button({ disabled: !allowed[key] });

I believe this should work, as it loops through and should keep the specified buttons enabled, however it does not seem to disable the others. Trying to debug through to see what I may be missing.

Angel

**Comment by KidSysco** [comment] 2016-09-26 14:52
Yes, this approach does work as we can see in the fiddle.

Put together a fiddle and we can take a look.

**Comment by tenshi04** [comment] 2016-09-26 18:06
I think there may be a slight bug when you click the year jump button. The enabled buttons doesn’t keep.

**Comment by tenshi04** [comment] 2016-09-26 19:54
How can I update the calendar’s Selected Month through code (jquery)?

Ex) some sort of click event on a graph, I want to set the month on the month-picker.

Thanks in advance.

**Comment by benjamin-albert** [comment] 2016-09-27 06:16
You can set the selected month using the [SelectedMonth option](https://github.com/KidSysco/jquery-ui-month-picker/wiki/SelectedMonth-Option)

**Comment by benjamin-albert** [comment] 2016-09-27 06:37
I've updated the [fiddle](http://jsfiddle.net/8x4nnvsj/5/) to address the issue with the Jump years button.

**Comment by tenshi04** [comment] 2016-09-27 14:58
Thanks! This awesome.

**Comment by tenshi04** [comment] 2016-09-27 15:01
I’m trying to do something like this:

$('#month-date-selector').MonthPicker('option', 'SelectedMonth', monthSelectorDate);

Where monthSelectorDate = “2007-01”

I have initialized the picker to have a format of yy-mm

When I try to make a call to set the selectedmonth, I get the following error:

Uncaught Error: cannot call methods on MonthPicker prior to initialization; attempted to call method 'option'

I know that the monthpicker has been initialized, because I can make selections on the monthpicker with no issues.

Any ideas?

**Comment by benjamin-albert** [comment] 2016-09-27 15:15
@tenshi04 Can you setup a fiddle that reproduces this problem?

**Comment by tenshi04** [comment] 2016-09-27 15:30
I’ll see if I can. It’s part of a larger project but I’ll try to pull out the essentials to put it in a fiddle.

**Comment by tenshi04** [comment] 2016-09-27 16:27
Give this one a try.

http://jsfiddle.net/99n6yjqe/2/

I just copied your fiddle and added a button that should set the monthpicker.

Angel

**Comment by benjamin-albert** [comment] 2016-09-27 17:28
I've updated [you're fiddle](http://jsfiddle.net/99n6yjqe/3/).

There were two issues there:

1. Since I subclassed `MonthPicker` you must call `$('.selector').ArbitraryMonthPicker()`.
2. You need to change your date string from `2016-08` to `08/2016`.

**Comment by tenshi04** [comment] 2016-09-27 17:33
For 2. What if the format that I had set on my own version was yy-mm ? Do we always need to set it as mm/yy ? ex) 08/2016 ?

**Comment by benjamin-albert** [comment] 2016-09-27 18:07
Assuming you set the `MonthFormat` option to `yy-mm`, you can pass ` 2016-08` to the `SelectedMonth` option.

I just pointed that out because it was an issue with the specific fiddle you sent us.

**Comment by tenshi04** [comment] 2016-09-27 18:11
Yes you’re right. I forgot to set the MonthFormat in the fiddle I sent.

So basically, I send the SelectedMonth in the same format as the MonthFormat.

Got it, I’ll give it a try.

**Comment by tenshi04** [comment] 2016-09-28 20:45
Hi Benjamin,

I am still working to setup a fiddle to re-create my issue with not being able to disable months, to mimic my scenario as much as possible.

Until then, I’d still like to ask about this particular line of code:

$('.button-' + i, menu).button({ disabled: !allowed[key] });

Can you explain to me what is actually happening here? I understand that we loop through all the 12 buttons and set a disabled property on .button ? What does this do on the menu object?

For some reason, the buttons are not getting disabled.

I tried my own version of doing this:

if (!allowed[key]) {
                $('.button-' + i).addClass("ui-button-disabled");
                $('.button-' + i).addClass("ui-state-disabled");
            } else {
                $('.button-' + i).removeClass("ui-button-disabled");
                $('.button-' + i).removeClass("ui-state-disabled");
            }

But this breaks when the user uses ‘Jump Years’.

Any insight would be great. I can’t seem to figure out why the month buttons aren’t being disabled.

thanks

**Comment by tenshi04** [comment] 2016-09-28 20:55
Not sure if this may affect it, but I am using jQuery 1.11.2

Angel

From: Angelbert David
Sent: Wednesday, September 28, 2016 2:45 PM
To: 'KidSysco/jquery-ui-month-picker' <reply@reply.github.com>; KidSysco/jquery-ui-month-picker <jquery-ui-month-picker@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [KidSysco/jquery-ui-month-picker] Set only specific months selectable (#64)

Hi Benjamin,

I am still working to setup a fiddle to re-create my issue with not being able to disable months, to mimic my scenario as much as possible.

Until then, I’d still like to ask about this particular line of code:

$('.button-' + i, menu).button({ disabled: !allowed[key] });

Can you explain to me what is actually happening here? I understand that we loop through all the 12 buttons and set a disabled property on .button ? What does this do on the menu object?

For some reason, the buttons are not getting disabled.

I tried my own version of doing this:

if (!allowed[key]) {
                $('.button-' + i).addClass("ui-button-disabled");
                $('.button-' + i).addClass("ui-state-disabled");
            } else {
                $('.button-' + i).removeClass("ui-button-disabled");
                $('.button-' + i).removeClass("ui-state-disabled");
            }

But this breaks when the user uses ‘Jump Years’.

Any insight would be great. I can’t seem to figure out why the month buttons aren’t being disabled.

thanks

**Comment by tenshi04** [comment] 2016-09-28 21:57
I think I figured it out with the help of this article:

http://stackoverflow.com/questions/34344237/button-jquery-ui-not-working

jquery ui button and bootstrap button weren’t playing nice.

I had to add this to my code:

(function() {
  var bootstrapButton = $.fn.button.noConflict();
  $.fn.bootstrapBtn = bootstrapButton;
}());


Hope this helps someone else.

Angel

From: Angelbert David
Sent: Wednesday, September 28, 2016 2:56 PM
To: 'KidSysco/jquery-ui-month-picker' <reply@reply.github.com>; 'KidSysco/jquery-ui-month-picker' <jquery-ui-month-picker@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [KidSysco/jquery-ui-month-picker] Set only specific months selectable (#64)

Not sure if this may affect it, but I am using jQuery 1.11.2

Angel

From: Angelbert David
Sent: Wednesday, September 28, 2016 2:45 PM
To: 'KidSysco/jquery-ui-month-picker' <reply@reply.github.com>; KidSysco/jquery-ui-month-picker <jquery-ui-month-picker@noreply.github.com<mailto:jquery-ui-month-picker@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [KidSysco/jquery-ui-month-picker] Set only specific months selectable (#64)

Hi Benjamin,

I am still working to setup a fiddle to re-create my issue with not being able to disable months, to mimic my scenario as much as possible.

Until then, I’d still like to ask about this particular line of code:

$('.button-' + i, menu).button({ disabled: !allowed[key] });

Can you explain to me what is actually happening here? I understand that we loop through all the 12 buttons and set a disabled property on .button ? What does this do on the menu object?

For some reason, the buttons are not getting disabled.

I tried my own version of doing this:

if (!allowed[key]) {
                $('.button-' + i).addClass("ui-button-disabled");
                $('.button-' + i).addClass("ui-state-disabled");
            } else {
                $('.button-' + i).removeClass("ui-button-disabled");
                $('.button-' + i).removeClass("ui-state-disabled");
            }

But this breaks when the user uses ‘Jump Years’.

Any insight would be great. I can’t seem to figure out why the month buttons aren’t being disabled.

thanks

**Comment by KidSysco** [comment] 2016-09-29 16:18
Interesting, there have been other bootstrap conflicts that we have run into before. This one is new. I kinda wish BootStrap would have just adopted  jQuery UI. Or that jQuery UI had adopted some sort of BootStrap type of mobile layout. Because it will soon get to be obvious that folks are going to try to use both together. 

I think it was pretty silly for the Bootstrap group to ignore jQuery UI while adopting jQuery. They are not really following their own advice there, which is to use something that is already well tested and ready to go rather than rolling your own. However, I have always kind of thought of the BootStrap group as a bunch of cowboys shooting their guns into the air.

**Comment by benjamin-albert** [comment] 2016-09-29 16:30
It's actually the exact same issue we had in #35.

We work around this issue in our code, but I don't workaround it in the example I setup.

**Comment by benjamin-albert** [comment] 2016-09-29 16:37
Another thing to note the workaround we use in our code is a private implementation detail and should not be used outside our code.

**Comment by KidSysco** [comment] 2016-09-30 12:47
@tenshi04 - If you don't mind me asking... Let's just call it a little market research.

I am assuming that you had a BootStrap based app already, then you needed a month picker. So you installed jQuery UI and this plugin next, which lead you to this problem.

Is that a fair assumption? Any insight you could provide is appreciated!

Thanks,

-Kid

**Comment by tenshi04** [comment] 2016-09-30 14:14
That is correct.

We were working on a Bootstrap based app and a requirement came in to be able to select distinct months (hence, the need to define which months are selectable). I added the plug-in, and for the most part everything was working out of the box except for the ability to set the disabled state to the button.

**Comment by tenshi04** [comment] 2016-10-04 14:42
Here’s another question for you guys – on the header, it says Year 2016 for example. How can I change this to just say 2016? Is there an option?

Thanks.

**Comment by benjamin-albert** [comment] 2016-10-04 14:55
Take a look at the [Multiple Language Support](https://github.com/KidSysco/jquery-ui-month-picker/wiki/Multiple-Language-Support) section of our wiki, It explains how to swap out any text used in the plugin.

Here is a quick example:
```js
$('.selector').MonthPicker({
  i18n: {
     year: ''
  }
});
```

**Comment by tenshi04** [comment] 2016-10-04 14:58
If I actually set it to '', it defaults it back to Year 2016.
If I set it to ‘Hello’, it sets it to Hello 2016, which is fine.
If I set it to ' ', then it ‘appears’ to be 2016 with the extra space I think preceding?

**Comment by KidSysco** [comment] 2016-10-04 15:05
That is what my tests show too. If it is blank, then the word Year still shows.

**Comment by benjamin-albert** [comment] 2016-10-04 15:06
Ouch.  You're right.

This is because it uses this common JS trick:
```js
 _i18n: function(str) {
   return this.options.i18n[str] || $.MonthPicker.i18n[str];
 },
```

An empty string is a `falsy` value in JavaScript so it uses the default value.

I'll open I pull request to fix this when I can find time for that.
Until then try this:
```js
$('.selector').MonthPicker({
  i18n: {
     year: '\r'
  }
});
```

**Comment by tenshi04** [comment] 2016-10-04 15:26
Thanks for the quick reply.

**Comment by KidSysco** [comment] 2016-10-07 13:35
Latest fix merged and we created a new release so we should be ready to close this one out now. Let us know if anything else comes up and thanks for your feedback!

**Closed by KidSysco** 2016-10-07 13:35 UTC

**Comment by benjamin-albert** [comment] 2016-10-07 17:03
@tenshi04 Thank you for opening an issue and helping us make this plugin better for everyone.

If you like this plugin please consider [Starring this repo](https://github.com/KidSysco/jquery-ui-month-picker/stargazers), It will go a long way helping us get this plugin on [cdnjs](https://cdnjs.com).
